// plugin-guide v1.2 —— 在 QuickJS 引擎中验证通过（语法/全章节/四模板/异常路径）
// 事实来源：plugin/PluginRepository.kt / PluginExecutor.kt / PluginConfigStore.kt / PluginWebView.kt

var SECTIONS = {};

SECTIONS.standards = [
  '# 开发规范（必读红线）',
  '',
  '与字段规则同级强制：违反 = 返工。任何插件动手前先过本章。',
  '',
  '## 交付纪律',
  '',
  '- 一次交付完整闭环：manifest.json + main.js（有 ui 则含 index.html）一次给全。禁止 TODO、占位符、"后续再补"的半成品',
  '- 同类问题同步修：一处正则/上限/字段写错，检查所有工具是否同样写错，一次改完',
  '- 不确定就停下：字段含义、参数类型、API 行为没把握时，先用 plugin_guide 核对，核对不到就问用户。禁止拿假设蒙混过关',
  '',
  '## 事实优先',
  '',
  '- 写代码前先查 manifest / mainjs / 相关功能章节；正则与上限以 limits 为准，不凭记忆写',
  '- 沙盒做不到的事直接说做不到：无 Node API、无计时器、无文件系统、fetch 仅 HTTPS 且同步、响应体 2MB 上限。需要这些能力时明确告知用户，不静默换方案绕过',
  '- 要换方案必须先给三样：原方案为什么不可行、两个方案的差异、决定权交还用户——用户决定，不是你',
  '',
  '## 错误处理红线',
  '',
  '- 参数校验、JSON.parse、fetch 调用等易错路径必须有显式错误处理',
  '- 禁止空 catch：每个 catch 要么处理、要么故意 rethrow，二选一',
  '- 禁止 console.log 顶替错误处理——沙盒里它是 no-op，等于把错误扔进黑洞',
  '- Error message 必须自带定位：工具名、字段名、当前值、HTTP 状态码（QuickJS 异常只有 message，没 stack，所以定位信息得自己写全）。message 会原样进审计日志，也别把密钥和用户数据塞进去',
  '',
  '## 工具描述质量',
  '',
  '- 每个工具的 description 写清"什么时候调、返回什么、什么时候不适用"——这是模型决定调用的唯一依据',
  '- 参数 description 同理；含糊的描述 = 模型乱传参 = 插件背锅'
].join('\n');

SECTIONS.manifest = [
  '# manifest.json 全字段',
  '',
  'manifest.json 大小必须在 2 字节 ~ 512 KB 之间，UTF-8 JSON，位于插件包根目录（ZIP 根层，或在最多 3 层深的子目录里，且全包只能有一个 manifest.json）。',
  '',
  '| 字段 | 必填 | 规则 |',
  '|---|---|---|',
  '| id | 是 | 3~128 位，必须字母/数字开头，只允许 A-Za-z0-9 . _ - 。安装目录名会把它里的非法字符替换成下划线 |',
  '| name | 是 | 非空，去首尾空格后最多 80 字 |',
  '| version | 否 | 默认 "0.0.0"，最多 32 字 |',
  '| description | 否 | 最多 300 字 |',
  '| tools | 否 | 工具数组，见 tools_schema 章节 |',
  '| allowedHosts | 否 | 网络白名单数组，见 fetch 章节 |',
  '| ui | 否 | 字符串路径，或 {"ui":{"entry":"ui/index.html"}}。entry 必须真实存在于包内、canonical 路径不能越出包目录、必须是文件 |',
  '| config | 否 | 配置字段数组，见 config 章节 |',
  '',
  '插件包根目录（manifest.json 所在目录）必须同时存在 main.js，否则安装失败。',
  '示例（含全部可选部分的结构）：',
  '    {',
  '      "id": "my-plugin",',
  '      "name": "我的插件",',
  '      "version": "1.0.0",',
  '      "description": "一句话说明",',
  '      "allowedHosts": ["api.example.com"],',
  '      "ui": "ui/index.html",',
  '      "config": [',
  '        {"name": "api_key", "label": "API 密钥", "type": "password", "required": true}',
  '      ],',
  '      "tools": [',
  '        {',
  '          "name": "my_tool",',
  '          "description": "工具说明（最多500字，会进系统提示给模型看）",',
  '          "parameters": [',
  '            {"name": "query", "type": "string", "description": "参数说明", "required": true}',
  '          ]',
  '        }',
  '      ]',
  '    }'
].join('\n');

SECTIONS.tools_schema = [
  '# tools 工具声明',
  '',
  'manifest 的 tools 数组每项：',
  '',
  '- name：必填。正则 ^[A-Za-z_][A-Za-z0-9_]{0,127}$，即字母或下划线开头，最长128位。执行时 main.js 里必须有 exports[name] 且为 function，否则报 "Tool not exported"',
  '- description：选填，截断到 500 字。这段会作为工具描述暴露给 AI 模型，写清楚什么时候该调',
  '- parameters：选填数组，每项：',
  '  - name：正则 ^[A-Za-z_][A-Za-z0-9_]{0,63}$（最长64）',
  '  - type：string / number / integer / boolean / array / object 之一，其他值一律按 string 处理',
  '  - description：截断到 300 字',
  '  - required：bool，true 的参数会进 schema 的 required 数组',
  '',
  '参数 schema 最终拼成 {type:"object", properties:{...}, required:[...], additionalProperties:false} 注册进工具系统。',
  '注意：参数类型只是声明，QuickJS 端拿到的就是模型给的 JSON 解析结果，number 可能是整数或浮点，记得自行容错。'
].join('\n');

SECTIONS.mainjs = [
  '# main.js 编写',
  '',
  '- 文件大小上限 2 MB，UTF-8',
  '- 在 QuickJS 引擎里执行，支持 ES2020（含 async/await、模板字符串、可选链），无 DOM、无 Node API',
  '- 每次工具调用都是全新引擎实例：全局变量不会跨调用泄漏，也不要指望模块级缓存状态',
  '',
  '引擎在执行你的代码前注入了三样东西：',
  '',
  '1. globalThis.exports = {} —— 把每个工具函数挂上去：exports.my_tool = function(args) { ... }',
  '2. globalThis.__MIKEKO_PLUGIN_CONFIG —— 当前插件配置的 JSON 字符串（无 config 则为 "{}"）。用 JSON.parse(__MIKEKO_PLUGIN_CONFIG) 读取',
  '3. globalThis.fetch(url, options) —— 受白名单限制的网络函数，详见 fetch 章节',
  '',
  '工具函数签名：function(args) —— args 是参数对象（模型传的 JSON 直接解析结果）。',
  '返回值：字符串原样返回给调用方；其他类型会被 JSON.stringify 后返回。抛异常 = 本次调用失败，message 会进审计日志。',
  '',
  'console.log 存在但是空实现（no-op），调试请把信息拼进返回值。',
  '最小示例：',
  '    exports.hello = function(args) {',
  '      return "hello " + String(args.name || "world");',
  '    };',
  '',
  '读配置示例：',
  '    exports.lookup = function(args) {',
  '      var cfg = JSON.parse(globalThis.__MIKEKO_PLUGIN_CONFIG || "{}");',
  '      var key = cfg.api_key || ""; // config 里声明的字段',
  '      if (!key) throw new Error("未配置 api_key");',
  '      ...',
  '    };'
].join('\n');

SECTIONS.sandbox = [
  '# 沙盒与安全机制',
  '',
  '- 单次工具调用整体超时 30 秒（withTimeout 30_000），超时直接失败',
  '- 每次调用独立 QuickJS 实例，插件间、调用间全局隔离',
  '- 无计时器/无 Node API/无文件系统访问',
  '- 网络只能走注入的 fetch（HTTPS + 白名单），OkHttp 客户端关闭了重定向跟随（followRedirects=false），3xx 会被视为非 2xx 结果，需要自己处理 Location',
  '- 每次调用写入审计日志：category=plugin、工具名、插件ID、success/error、耗时毫秒、错误信息',
  '- UI 侧另有独立限制，见 ui 章节'
].join('\n');

SECTIONS.fetch = [
  '# fetch 与 allowedHosts',
  '',
  'main.js 里的 fetch(url, options) 是宿主桥接的 OkHttp 请求：',
  '',
  '- 返回值：{ok: bool, status: number, body: string}，失败时多个 error 字段。ok = HTTP 状态 2xx',
  '- 超时：连接 10s / 读写 20s',
  '- 强制 HTTPS，http:// 直接被拒',
  '',
  '白名单规则：',
  '',
  '- manifest 的 allowedHosts 数组，每项是一个 host（写 URL 也行但必须 https，会自动取 host）',
  '- 不允许 "*"（禁止无限制域名）',
  '- host 只能由 a-z 0-9 . - 组成，不能以点开头或结尾',
  '- 匹配：请求 host 完全相等，或是其子域（host.endsWith("." + 白名单项)）。写 "example.com" 可覆盖 "api.example.com"',
  '',
  'options 支持：',
  '',
  '- method：GET / POST / PUT / PATCH / DELETE（大写化后校验）',
  '- headers：对象。禁止设置 host / content-length / connection，其余头值截断到 8192 字',
  '- body：字符串，最长 1,000,000 字符。Content-Type 从 headers 里取',
  '',
  '响应体超过 2 MB 直接报错。',
  '示例（GET）：',
  '    var res = fetch("https://api.example.com/v1/data", {',
  '      method: "GET",',
  '      headers: {"Authorization": "Bearer " + key}',
  '    });',
  '    if (!res.ok) throw new Error("HTTP " + res.status + ": " + res.body);',
  '    var data = JSON.parse(res.body);',
  '',
  '注意：注入的 fetch 是同步风格调用（宿主在协程里阻塞执行），不要加 await 也不要自己包 Promise。'
].join('\n');

SECTIONS.ui = [
  '# UI 插件（WebView）',
  '',
  'manifest 里 ui 指向包内一个 html 文件（如 "ui/index.html"），插件列表页会出现打开入口。',
  '',
  '运行机制：',
  '',
  '- WebView 以虚拟域 https://plugin.invalid/<相对路径> 加载包内文件，本地资源由请求拦截器提供，单文件上限 5 MB',
  '- entry 是 html/htm 时，自动在 <head> 之后注入桥脚本（没有 head 标签则拼在最前面）',
  '- 页面外链（脚本/样式/图片/XHR）必须 HTTPS 且 host 命中 allowedHosts，否则 403 "Blocked by Mikeko plugin policy"',
  '- 主框架导航只允许 plugin.invalid，跳外站会被拦截；file/content 协议全禁',
  '- 混合内容全禁（MIXED_CONTENT_NEVER_ALLOW），safeBrowsing 开启',
  '',
  '注入的桥（仅 UI 侧）：',
  '',
  '    orangeisland.config          // 配置对象（不是字符串，UI 侧直接是对象）',
  '    orangeisland.call(name, args, callback)   // 调本插件声明的工具函数',
  '    window.Bridge                // 同 orangeisland 的别名',
  '',
  'call 的约束：只能调本插件 manifest 里声明的工具；插件必须处于启用状态；callbackId 1~32 位。结果以字符串回传给 callback（工具函数返回的原文）。',
  '',
  '示例 index.html 片段：',
  '    <button onclick="run()">查询</button>',
  '    <script>',
  '      function run() {',
  '        orangeisland.call("my_tool", {query: "hi"}, function(result) {',
  '          document.body.textContent = String(result);',
  '        });',
  '      }',
  '    </script>',
  '',
  '关闭 UI 时 WebView 销毁并移除 JS 接口；重开是全新实例。'
].join('\n');

SECTIONS.config = [
  '# config 配置项',
  '',
  'manifest 的 config 数组每项：',
  '',
  '- name：必填。正则 ^[A-Za-z_][A-Za-z0-9_]{0,63}$',
  '- label：界面显示名，默认取 name，截断 80 字',
  '- description：说明，截断 240 字',
  '- required：bool。为 true 时：保存校验非空；插件启用前必须已填',
  '- type："password" 会按密钥处理。另外 name 里含 key / token / password / secret（不区分大小写）也自动按密钥处理',
  '',
  '存储分级：',
  '',
  '- 密钥字段 → Android Keystore 加密保管（ApiKeyVault），卸载插件时同步删除',
  '- 普通字段 → SharedPreferences（next_plugin_config，按插件ID分组）',
  '',
  'main.js 里通过 __MIKEKO_PLUGIN_CONFIG 读到的是合并后的明文 JSON 字符串；UI 侧通过 orangeisland.config 直接拿对象。',
  '安装后插件默认停用；有 required 字段没填时无法启用（报 "请先填写 xxx"）。'
].join('\n');

SECTIONS.install = [
  '# 安装包与安装流程',
  '',
  'ZIP 包要求：',
  '',
  '- 最多 500 个条目，解压后总大小 ≤ 25 MB',
  '- manifest.json 恰好一个；查找范围：解压后目录树向下最多 3 层',
  '- manifest 所在目录 = 包根，包根必须有 main.js',
  '- 条目名做 canonical 路径校验，防路径穿越（../ 之类直接拒）',
  '',
  '安装动作：',
  '',
  '1. 解压到临时 staging 目录',
  '2. 校验 manifest → 定位包根 → 校验 main.js 存在',
  '3. 复制到 files/next-plugins/<id安全化后的目录名>（同名即覆盖重装，旧目录整个删掉）',
  '4. 列表刷新，弹 "插件 xxx 已安全安装"',
  '',
  '装完默认停用，要在插件页手动开开关。卸载会连带清掉：目录、普通配置、密钥、启用标志。',
  '插件工具只在插件启用后进入 AI 的工具系统（PluginTool 枚举自 manifest 的 tools）。'
].join('\n');

SECTIONS.limits = [
  '# 限制速查表',
  '',
  '| 项 | 上限 |',
  '|---|---|',
  '| manifest.json | 2 B ~ 512 KB |',
  '| main.js | 2 MB |',
  '| 插件包 | 500 文件 / 解压 25 MB |',
  '| 工具名 | 128 位 |',
  '| 工具参数名 | 64 位 |',
  '| 工具 description | 500 字 |',
  '| 参数 description | 300 字 |',
  '| name | 80 字 |',
  '| description | 300 字 |',
  '| version | 32 字 |',
  '| config label / description | 80 / 240 字 |',
  '| 工具执行 | 30 秒超时 |',
  '| HTTP body | 1 MB |',
  '| HTTP 响应体 | 2 MB |',
  '| HTTP 单头值 | 8192 字 |',
  '| UI 单资源文件 | 5 MB |',
  '| UI callback ID | 1~32 位 |',
  '| 网络 | 仅 HTTPS + allowedHosts 白名单（禁 * ）|',
  '| HTTP 方法 | GET/POST/PUT/PATCH/DELETE |'
].join('\n');

SECTIONS.audit = [
  '# 审计',
  '',
  '每次插件工具调用（成功或失败）写一条 CallAuditLog：',
  '',
  '- category："plugin"',
  '- 工具名、插件 ID',
  '- 结果：success / error（附错误 message）',
  '- 耗时毫秒',
  '',
  '应用内有审计日志页可查。UI 侧 call 走同一条链路。写插件时抛出的 Error message 会原样进日志，别在 message 里放敏感数据。'
].join('\n');

SECTIONS.workflow_sample = [
  '# 官方范例参照',
  '',
  '仓库自带 workflow-field-guide 插件（plugins/workflow-field-guide/），是纯工具插件的范本：',
  '',
  '- manifest：id + name + version + description + 两个 tools（查询字段字典 / 渲染工作流），无 allowedHosts、无 ui、无 config',
  '- main.js：纯数据字典 + 渲染逻辑，exports 导出两个函数，按 section 参数返回 markdown',
  '- 打包：目录压 ZIP，manifest.json 与 main.js 在根层，导入即装',
  '',
  '本指南插件（plugin-guide）与其同构，可以对照着看。'
].join('\n');

SECTIONS.troubleshooting = [
  '# 常见错误对照',
  '',
  '| 报错 | 原因 |',
  '|---|---|',
  '| 插件包必须且只能包含一个 manifest.json | ZIP 里有多个 manifest，或藏得比 3 层深 |',
  '| 插件缺少 main.js | manifest 同目录没有 main.js |',
  '| 插件 ID 格式无效 | 不满足 ^[A-Za-z0-9][A-Za-z0-9._-]{2,127}$ |',
  '| 插件 UI 路径无效 | ui 指向的文件不存在 / 路径越出包目录 |',
  '| Tool not exported | main.js 里没 exports.工具名，或不是 function |',
  '| 插件只能访问 HTTPS | fetch 了 http:// |',
  '| Host ... 不在插件网络白名单 | allowedHosts 没写该域名（或没写其父域） |',
  '| 不允许无限制网络域名 | allowedHosts 里写了 "*" |',
  '| 不允许设置请求头 ... | headers 里设了 host/content-length/connection |',
  '| 插件网络响应超过 2 MB | 响应体超限 |',
  '| 插件包文件数量超过 500 / 解压后不能超过 25 MB | 包体超限 |',
  '| main.js 不能超过 2 MB | 源码超限 |',
  '| 请先填写 xxx | 启用时有 required 配置没填 |',
  '| UI 403 Blocked by Mikeko plugin policy | 外链资源 host 不在白名单或非 https |',
  '| 未声明的插件工具 | UI 桥 call 了 manifest 里没有的工具，或插件没启用 |',
  '| 调用失败但审计里没有错误信息 | 空 catch 吞了错误，或只 console.log（no-op）——违反 standards 红线 |'
].join('\n');

var TEMPLATES = {};

TEMPLATES.minimal = [
  '# 模板：纯工具插件（minimal）',
  '',
  '目录结构：',
  '    my-plugin/',
  '    ├── manifest.json',
  '    └── main.js',
  '',
  '== manifest.json ==',
  '    {',
  '      "id": "my-plugin",',
  '      "name": "我的插件",',
  '      "version": "1.0.0",',
  '      "description": "一句话说明这个插件让 AI 能做什么。",',
  '      "tools": [',
  '        {',
  '          "name": "my_tool",',
  '          "description": "什么时候调这个工具、返回什么。",',
  '          "parameters": [',
  '            {"name": "query", "type": "string", "description": "查询内容", "required": true}',
  '          ]',
  '        }',
  '      ]',
  '    }',
  '',
  '== main.js ==',
  '    exports.my_tool = function(args) {',
  '      var q = String(args.query || "").trim();',
  '      if (!q) throw new Error("query 不能为空");',
  '      return "结果：" + q;',
  '    };',
  '',
  '打包：把 my-plugin 目录压成 ZIP（manifest.json 在根层），插件页导入，启用。'
].join('\n');

TEMPLATES.network = [
  '# 模板：联网插件（network）',
  '',
  '== manifest.json ==',
  '    {',
  '      "id": "http-demo",',
  '      "name": "HTTP 示例",',
  '      "version": "1.0.0",',
  '      "description": "调用白名单域名 API 的示例。",',
  '      "allowedHosts": ["api.example.com"],',
  '      "tools": [',
  '        {',
  '          "name": "fetch_data",',
  '          "description": "从 api.example.com 拉数据。",',
  '          "parameters": [',
  '            {"name": "path", "type": "string", "description": "API 路径，如 /v1/data", "required": true}',
  '          ]',
  '        }',
  '      ]',
  '    }',
  '',
  '== main.js ==',
  '    exports.fetch_data = function(args) {',
  '      var path = String(args.path || "/");',
  '      if (path.indexOf("/") !== 0) path = "/" + path;',
  '      var res = fetch("https://api.example.com" + path, { method: "GET" });',
  '      if (!res.ok) throw new Error("HTTP " + res.status + ": " + String(res.body).slice(0, 500));',
  '      return res.body; // 大多数 API 直接把 JSON 字符串返回即可',
  '    };',
  '',
  '要点：域名必须先写进 allowedHosts；只有 https；子域自动覆盖（写 example.com 可调 api.example.com）；fetch 是同步风格，不要 await。'
].join('\n');

TEMPLATES.ui = [
  '# 模板：带界面插件（ui）',
  '',
  '目录结构：',
  '    ui-demo/',
  '    ├── manifest.json',
  '    ├── main.js',
  '    └── ui/',
  '        └── index.html',
  '',
  '== manifest.json ==',
  '    {',
  '      "id": "ui-demo",',
  '      "name": "界面示例",',
  '      "version": "1.0.0",',
  '      "description": "带 WebView 界面的插件示例。",',
  '      "ui": "ui/index.html",',
  '      "tools": [',
  '        {',
  '          "name": "greet",',
  '          "description": "返回问候语，供界面调用。",',
  '          "parameters": [',
  '            {"name": "name", "type": "string", "description": "名字", "required": true}',
  '          ]',
  '        }',
  '      ]',
  '    }',
  '',
  '== main.js ==',
  '    exports.greet = function(args) {',
  '      return "你好，" + String(args.name || "朋友") + "！";',
  '    };',
  '',
  '== ui/index.html ==',
  '    <!DOCTYPE html>',
  '    <html><head><meta charset="utf-8"><title>ui-demo</title></head>',
  '    <body>',
  '      <input id="name" placeholder="输入名字">',
  '      <button onclick="run()">打招呼</button>',
  '      <p id="out"></p>',
  '      <script>',
  '        function run() {',
  '          var name = document.getElementById("name").value;',
  '          orangeisland.call("greet", {name: name}, function(result) {',
  '            document.getElementById("out").textContent = String(result);',
  '          });',
  '        }',
  '      </script>',
  '    </body></html>',
  '',
  '要点：ui 路径相对包根；外链资源必须 https 且在 allowedHosts 内，尽量全内联；桥对象名 orangeisland（别名 Bridge）。'
].join('\n');

TEMPLATES.config = [
  '# 模板：带配置插件（config）',
  '',
  '== manifest.json ==',
  '    {',
  '      "id": "config-demo",',
  '      "name": "配置示例",',
  '      "version": "1.0.0",',
  '      "description": "带密钥配置的插件示例。",',
  '      "allowedHosts": ["api.example.com"],',
  '      "config": [',
  '        {"name": "api_key", "label": "API 密钥", "description": "在 example.com 申请", "type": "password", "required": true},',
  '        {"name": "base_path", "label": "默认路径", "description": "选填", "required": false}',
  '      ],',
  '      "tools": [',
  '        {',
  '          "name": "ping",',
  '          "description": "用配置的密钥测试连通。",',
  '          "parameters": []',
  '        }',
  '      ]',
  '    }',
  '',
  '== main.js ==',
  '    exports.ping = function(args) {',
  '      var cfg = JSON.parse(globalThis.__MIKEKO_PLUGIN_CONFIG || "{}");',
  '      var key = String(cfg.api_key || "");',
  '      if (!key) throw new Error("请先在插件配置里填写 api_key");',
  '      var res = fetch("https://api.example.com" + String(cfg.base_path || "/ping"), {',
  '        method: "GET",',
  '        headers: {"Authorization": "Bearer " + key}',
  '      });',
  '      if (!res.ok) throw new Error("HTTP " + res.status);',
  '      return res.body;',
  '    };',
  '',
  '要点：api_key 因 type=password 进 Keystore 加密存储；required 未填无法启用；配置在 main.js 里是 __MIKEKO_PLUGIN_CONFIG 字符串，在 UI 里是 orangeisland.config 对象。'
].join('\n');

function toc() {
  return ['Mikeko 插件开发指南 —— 章节目录', '',
    'standards        开发规范（必读：交付纪律/事实优先/错误处理红线）',
    'manifest         manifest.json 全字段规则',
    'tools_schema     工具声明与参数 schema',
    'mainjs           main.js 编写（exports/配置/注入环境）',
    'sandbox          沙盒与安全机制',
    'fetch            fetch 与 allowedHosts 白名单',
    'ui               UI 插件（WebView + orangeisland 桥）',
    'config           配置项与密钥存储',
    'install          安装包格式与流程',
    'limits           全部限制速查表',
    'audit            审计日志',
    'workflow_sample  官方范例参照',
    'troubleshooting  常见错误对照表', '',
    '另一个工具 plugin_template(kind) 输出可直接复制的模板：minimal / network / ui / config', '',
    '提示：开发插件前先查 manifest + mainjs + 对应功能的章节，交付前用 limits 核对上限。'].join('\n');
}

exports.plugin_guide = function(args) {
  var section = args && args.section ? String(args.section).trim().toLowerCase() : "all";
  if (section === "all" || section === "") {
    var parts = [toc()];
    var order = ["standards", "manifest", "tools_schema", "mainjs", "sandbox", "fetch", "ui", "config", "install", "limits", "audit", "workflow_sample", "troubleshooting"];
    for (var i = 0; i < order.length; i++) parts.push("\n\n---\n\n" + SECTIONS[order[i]]);
    return parts.join("");
  }
  if (!Object.prototype.hasOwnProperty.call(SECTIONS, section)) {
    throw new Error("未知章节：" + section + "。可用：" + Object.keys(SECTIONS).join(", "));
  }
  return SECTIONS[section];
};

exports.plugin_template = function(args) {
  var kind = args && args.kind ? String(args.kind).trim().toLowerCase() : "minimal";
  if (!Object.prototype.hasOwnProperty.call(TEMPLATES, kind)) {
    throw new Error("未知模板：" + kind + "。可用：" + Object.keys(TEMPLATES).join(", "));
  }
  return TEMPLATES[kind];
};
